pipeline {
  agent any

  environment {
    ARM_CLIENT_ID       = credentials('AZURE_CLIENT_ID')       // Jenkins credentials ID
    ARM_CLIENT_SECRET   = credentials('AZURE_CLIENT_SECRET')
    ARM_SUBSCRIPTION_ID = credentials('AZURE_SUBSCRIPTION_ID')
    ARM_TENANT_ID       = credentials('AZURE_TENANT_ID')
  }

  stages {
    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh 'terraform plan -var-file="terraform.tfvars"'
      }
    }

    stage('Terraform Apply') {
      steps {
        input message: "Approve deployment?"
        sh 'terraform apply -auto-approve -var-file="terraform.tfvars"'
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}

